name: IndexNow
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  indexnow:
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: bojieyang/indexnow-action@38ddfbd93579a8a44c0dee662121bf9d51098f71 # v3.0.0
        with:
          sitemap-location: "https://samkhan.net/sitemap.xml"
          key: ${{ secrets.INDEXNOW_KEY }}
